### ISSUE TITLE
Decoding biases String

### ISSUE THREAD

**Issue by WilliamDavy-DM** [edonv/JSONValue#1]
The JSONValue init from decoder biases strings but should instead try numbers and booleans first.  See the patch.  I have a BSONDecoder that is otherwise has the correct type for the field but always results in string values.  Proposed fix is to move the conditional check for string decoding below Double and Boolean.
[JSONValue-stringhandling.patch](https://github.com/edonv/JSONValue/files/13904647/JSONValue-stringhandling.patch)

**Comment by edonv** [comment]
Done!
